### ISSUE TITLE
No provider of 'prometheus-hanadb_exporter' found.

### ISSUE THREAD

**Issue by chainhead** [SUSE/hanadb_exporter#104]
I am trying to install this exporter with `zypper` on AWS EC2 machine running SLES. However, it fails with message as `No provider of 'prometheus-hanadb_exporter' found.`. What is missing?

```bash
zypper install prometheus-hanadb_exporter
Refreshing service 'Basesystem_Module_x86_64'.
Refreshing service 'Containers_Module_x86_64'.
Refreshing service 'Desktop_Applications_Module_x86_64'.
Refreshing service 'Development_Tools_Module_x86_64'.
Refreshing service 'Legacy_Module_x86_64'.
Refreshing service 'Public_Cloud_Module_x86_64'.
Refreshing service 'SUSE_Cloud_Application_Platform_Tools_Module_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Server_x86_64'.
Refreshing service 'Server_Applications_Module_x86_64'.
Refreshing service 'Web_and_Scripting_Module_x86_64'.
Loading repository data...
Reading installed packages...
'prometheus-hanadb_exporter' not found in package names. Trying capabilities.
```

**Comment by arbulu89** [comment]
@chainhead This package is provided in SLES4SAP subscription, and not plain SLES. As far as I see you are using a plain SLES distro, so this might be the problem

**Comment by chainhead** [comment]
@arbulu89 So, the following instructions from [here](https://software.opensuse.org//download.html?project=openSUSE%3AFactory&package=prometheus-hanadb_exporter) also wouldn't go through? (Yes, I am a SAP and SUSE Linux n00b).

```bash
zypper addrepo https://build.opensuse.org/repositories/openSUSE:Factory/standard/openSUSE:Factory.repo
zypper refresh
zypper install prometheus-hanadb_exporter
```

**Comment by arbulu89** [comment]
Yes, including this repository should make the package available. But you wouldn't receive any official support from it.
I don't really understand why the `addrepo` command fails...
