### ISSUE TITLE
CI: Update the Project and CI to latest versions of python and the base OS

### ISSUE THREAD

**Issue by diegoakechi** [SUSE/hanadb_exporter#113]
There are major current versions of Python above 3.6 and in some distros, 3.6 is not even available anymore causing issues on the current CI.

**Comment by madhurireddy** [comment]
I am also running into issues after upgrading python to 3.6, this hanadb_exporter does not work anymore.

**Comment by madhurireddy** [comment]
@arbulu89 please get this working for 3.6 and later versions of python please

**Comment by stefanotorresi** [comment]
CI updated to test with 3.6, 3.8 and 3.11
