### ISSUE TITLE
Connect to System DB on HANA 2

### ISSUE THREAD

**Issue by mduesi** [SUSE/hanadb_exporter#33]
Is it possible to connect to a HANA 2 instance to the system database? I can not find the according parameter in the config.json to set the database.

Thanks,
Marcus

**Comment by diegoakechi** [comment]
@mduesi the SYSTEMDB has a special port (3xx13). In theory (as I didn't personally try) it would be enough to point it to this port. Can you give it a try and let us know about the result?

**Comment by mduesi** [comment]
@diegoakechi Thank you, it worked.

**Comment by MalloZup** [comment]
@mduesi thx for feedback! closing
