### ISSUE TITLE
Question: GRAFANA Dashboards for Metrics?

### ISSUE THREAD

**Issue by freddiko** [SUSE/hanadb_exporter#52]
Hi, 

has someone already build grafana dashboards on the exposed metrics and is able to share them? Would be grad to also make the visualisation/alerting part available.

Best,

**Comment by arbulu89** [comment]
Hi @freddiko ,
Yes, we have a dashboard using this metrics in the project: https://github.com/SUSE/ha-sap-terraform-deployments

Actually, using this project everything is automatized. 
Anyway, find the current dashboard in (to use it, you will need to configure prometheus server, the exporters, and grafana server):
https://github.com/SUSE/ha-sap-terraform-deployments/blob/master/salt/monitoring/provisioning/dashboards/ha-sap-hana-detailed-timestamp.json

**Comment by freddiko** [comment]
This is amazing! Thank you so much.
