### ISSUE TITLE
Automatic login to grafana by token url from application angular

### ISSUE THREAD

**Issue by aelogri** [SUSE/hanadb_exporter#63]
Hello, 

I have an application developed with angular, which displays some metric from prometheus.

I have keycloak which managed the authentication for my angular application as well as for my grafana, it is an sso logic.

In my angular application I have a link that redirects to grafana.

I want the client to be authenticated directly without entering the login and password again in grafana.

N.P: I have access to the token in my angular application.

Thank you!

**Comment by stefanotorresi** [comment]
@aelogri I'm not sure why are you opening an issue here, this project is just a backend service to export Prometheus metrics, Grafana is an entirely different project! :)

You may want to post your inquiry in https://community.grafana.com.
