### ISSUE TITLE
TypeError: QueryResult object does not support indexing

### ISSUE THREAD

**Issue by chrkli193** [SUSE/hanadb_exporter#8]
Is this also supported for HANA 2.0 Databases. I get the following Error:

INFO:shaptools.hdb_connector.connectors.base_connector:pyhdb package loaded
INFO:shaptools.hdb_connector.connectors.base_connector:connecting to SAP HANA database at XXXXXXXXX:30013
INFO:shaptools.hdb_connector.connectors.base_connector:connected successfully
INFO:hanadb_exporter:prometheus exporter selected
INFO:shaptools.hdb_connector.connectors.base_connector:executing sql query: SELECT ROUND(SUM(total_memory_used_size/1024/1024),2) used_memory_mb FROM m_service_memory;
INFO:shaptools.hdb_connector.connectors.base_connector:query records: [(Decimal('10907.01'),)]
Traceback (most recent call last):
  File "app.py", line 56, in <module>
    main()
  File "app.py", line 51, in main
    REGISTRY.register(collector)
  File "/srv/hanadb_exporter/virt/local/lib/python2.7/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/srv/hanadb_exporter/virt/local/lib/python2.7/site-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "/srv/hanadb_exporter/hanadb_exporter/exporters/prometheus_exporter.py", line 77, in collect
    metric_obj = self._execute(metric)
  File "/srv/hanadb_exporter/hanadb_exporter/exporters/prometheus_exporter.py", line 50, in _execute
    metric_obj = self._manage_gauge(metric, value)
  File "/srv/hanadb_exporter/hanadb_exporter/exporters/prometheus_exporter.py", line 65, in _manage_gauge
    metric_obj.add_metric([], str(value[0][0]))
TypeError: 'QueryResult' object does not support indexing

**Comment by diegoakechi** [comment]
Hi @chrkli193,

Thanks for checking our project. Yes, it is intended to support HANA 2.0, and we are currently working to improve the way the queries are configured and the results parsed by the exporter. You can follow this on this PR https://github.com/SUSE/hanadb_exporter/pull/7.

To help you to get it running, can you say what exact HANA 2 version are you using at the moment?

**Comment by chrkli193** [comment]
Thanks four your fast response, it is HANA2 SP03

**Comment by ayoub-belarbi** [comment]
Hi @chrkli193, 
Like mentioned by @diegoakechi , it looks like the mentioned PR #7 will fix your issue. It will be great if you test the PR and let us know if the problem persist.

**Comment by diegoakechi** [comment]
@chrkli193 I could simulate your problem when I had an old version of shaptools installed on my virtual env together with the PR #7 checked out.

As this project is a very early stage and we have been changing then quite frequently, please, make sure to always check if you are using the latest versions. If you are using virtualenv, I recommend you to do a cleanup on it. For example:
`virtualenv --clear virt`

**Comment by chrkli193** [comment]
(virt) root@ubuntu:/srv/hanadb2# python3 app.py
INFO:shaptools.hdb_connector.connectors.base_connector:pyhdb package loaded
INFO:shaptools.hdb_connector.connectors.base_connector:connecting to SAP HANA database at XXXXXXX:30013
INFO:shaptools.hdb_connector.connectors.base_connector:connected successfully
INFO:hanadb_exporter:prometheus exporter selected
INFO:shaptools.hdb_connector.connectors.base_connector:executing sql query: SELECT ROUND(SUM(TOTAL_MEMORY_USED_SIZE/1024/1024/1024), 2) AS "Used Memory GB" FROM M_SERVICE_MEMORY;
INFO:shaptools.hdb_connector.connectors.base_connector:query records: [(Decimal('10.67'),)]
Traceback (most recent call last):
  File "app.py", line 56, in <module>
    main()
  File "app.py", line 51, in main
    REGISTRY.register(collector)
  File "/usr/lib/python3.5/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/usr/lib/python3.5/site-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "/srv/hanadb2/hanadb_exporter/exporters/prometheus_exporter.py", line 77, in collect
    metric_obj = self._execute(metric)
  File "/srv/hanadb2/hanadb_exporter/exporters/prometheus_exporter.py", line 50, in _execute
    metric_obj = self._manage_gauge(metric, value)
  File "/srv/hanadb2/hanadb_exporter/exporters/prometheus_exporter.py", line 65, in _manage_gauge
    metric_obj.add_metric([], str(value[0][0]))
TypeError: 'QueryResult' object does not support indexing

**Comment by chrkli193** [comment]
That looks much better

**Comment by diegoakechi** [comment]
@chrkli193 Ok, I am assuming it has worked. That is great! Let us know if you have any feedback...

**Comment by chrkli193** [comment]
Yes it worked. I will now add it to Prometheus

**Comment by diegoakechi** [comment]
@chrkli193 Ok, so I will close this issue for now. Please, open new issues if you have more problems or feedback.
