### ISSUE TITLE
Not displaying some Metrics for a Single Container System

### ISSUE THREAD

**Issue by pipinstallyogi** [SUSE/hanadb_exporter#80]
Hallo Everyone,
We have two HANA Databases _HD1_ and _HD2_.
Whereas the first one (HD1) is single container System, on the other hand HD2 is multi tenant. 
The _hanadb_exporter_ is running fine for both systems with setting "_multi_tenant_": _false_ for HD1 and "_multi_tenant_": _true_ for HD2 and the requisite address and ports in the configuration file.
However, the exported metrics are quite different in both the cases.
Some metrics might be based on the multi tenancy factors but there are some which should generally be shown by both of them. These are mostly related to _cpu_, _network_ and _disk_ statistics.

The following metrics are shown by HD2 (which is multi tenant) but not by HD1(which is single container System):

_hanadb_cpu_user_percent_
_hanadb_cpu_system_percent_
_hanadb_cpu_waitio_percent_
_hanadb_cpu_busy_percent_
_hanadb_cpu_idle_percent_
_hanadb_network_collisions_per_seconds_
_hanadb_network_receive_rate_kb_per_seconds_
_hanadb_network_transmission_rate_kb_per_seconds_
_hanadb_network_receive_requests_per_seconds_
_hanadb_network_transmission_rate_requests_per_seconds_
_hanadb_network_receive_rate_errors_per_seconds_
_hanadb_network_transmission_rate_errors_per_seconds_
_hanadb_disk_total_device_size_mb_
_hanadb_disk_total_size_mb_
_hanadb_disk_total_used_size_mb_
_hanadb_disk_used_size_mb_
_hanadb_disk_io_queue_length_requests_
_hanadb_disk_io_latency_ms_
_hanadb_disk_io_service_time_ms_
_hanadb_disk_io_wait_time_ms_
_hanadb_disk_io_requests_per_second_
_hanadb_disk_io_throughput_kb_second_

These metrics seem to be very important to get the correct picture about system load and Performance. Please provide some insights about the possible reason why the single container system HD1 is not able to extract these metrics. Any help and inputs about the same is highly appreciated. 
Thanks in advance

**Comment by diegoakechi** [comment]
@pipinstallyogi Can you check and provide the logs of the exporter? It logs the queries execution and also if some of them are failing.

**Comment by arbulu89** [comment]
Hi @pipinstallyogi ,
Thank you for reporting this issue. To add some context:
The `hanadb_exporter` collects the data after running the queries based on https://github.com/SUSE/hanadb_exporter/blob/master/metrics.json

Here some more information about how to modify the `metrics.json` file: https://github.com/SUSE/hanadb_exporter/blob/master/docs/METRICS.md

By default, we don't exclude any of the queries neither for HANA 1.0 or HANA 2.0 (except 2, that were included as examples and maybe we should update them, but they shouldn't have any impact).

After this, being honest, I have never tried the exporter in a HANA 1.0 database, so I didn't face this differences. 
When we start the exporter we run a basic query to get the current database version, and based on that, run or not the queries.
The query is:
```SELECT (SELECT value FROM M_SYSTEM_OVERVIEW WHERE section = 'System' AND name = 'Instance ID') SID, (SELECT value FROM M_SYSTEM_OVERVIEW WHERE section = 'System' AND name = 'Instance Number') INSNR, m.database_name, m.version FROM m_database m;```

Could you run this query in your single container database and print the output? Maybe we can find something with this

**Comment by pipinstallyogi** [comment]
Thanks @arbulu89 and @diegoakechi for the inputs. 

As @arbulu89 stated the query it is giving an output in single container system as:
SID    INSNR        DATABASE_NAME      VERSION
HD1    02                HD1                         1.00.122.06.1485334242

However, as @diegoakechi mentioned I have checked the log files for single container system and with some of the queries the error is because of the reason "Table not found" such as :

2020-10-13 12:34:45,153 ERROR hanadb_exporter.prometheus_exporter query failed: invalid table name:  Could not find table/view M_HOST_AGENT_METRICS in schema SYS: line 1 col 505 (at pos 504)

and

2020-10-13 12:34:45,152 ERROR hanadb_exporter.prometheus_exporter Failure in query: SELECT host, disk, queue_length, srv_ms + wait_ms latency_ms, srv_ms, wait_ms, io_per_s, tp_kbps FROM( SELECT MAX(TIMESTAMP) timestamp, host,     measured_element_name disk, MAX(MAP(caption, 'Queue Length', TO_NUMBER(value), 0)) queue_length, MAX(MAP(caption, 'Service Time', TO_NUMBER(value), 0)) srv_ms, MAX(MAP(caption, 'Wait Time', TO_NUMBER(value), 0)) wait_ms, MAX(MAP(caption, 'I/O Rate', TO_NUMBER(value), 0)) io_per_s, MAX(MAP(caption, 'Total Throughput', TO_NUMBER(value), 0)) tp_kbps FROM sys.m_host_agent_metrics WHERE measured_element_type = 'Disk' GROUP BY host, measured_element_name);, skipping...

On the other hand the log files for multi tenant system does not have any error reports but just warnings.

I guess the problem is that with single container systems the table names might be different and therefore exporter is not able to fetch the values from the table (because it does not find the table). I can verify this is with SQL command as well. When I am Querying HD2 (multi tenant) I am getting a reply but with the same query HD1 throws an error "invalid table name:  Could not find table/view ".

Or do you think of any other issue?
Thanks in advance

**Comment by diegoakechi** [comment]
Hi @pipinstallyogi 

I see you are running HANA 1 on HD1. The table M_HOST_AGENT_METRICS was introduced on HANA 2, so I believe that is why it does not exist on your system. See below the release notes.

https://help.sap.com/doc/d25e2e530606453c9866c695298423b3/2.0.02/en-US/Whats_New_SAP_HANA_Platform_Release_Notes_en.pdf

With that, you will need to adapt this SQL query to generate the metrics on HANA 1 with the existing monitoring tables provided by SAP on this HANA version. 

You can find the Views Reference on this link: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/1.0.12/en-US

Is HD2 running what HANA version?

**Comment by pipinstallyogi** [comment]
Hi @diegoakechi, you are absolutely right with this.
I have checked with few more table names and column names. Either a table with the same name is not in the single container system(HD1) or in some cases the column name is different with a similar table name. hence the exporter is unable to reply to a query.
You are right that I have to adapt the SQL queries to generate metrics on HD1 based on the table names in HD1 and then adding them to `metrics.json` file.

I will try to update queries here if they work for me.
Thanks a lot for helping me out with the issue.
Best.

**Comment by pipinstallyogi** [comment]
@diegoakechi Sure I will.
Also thanks for the link to Views reference.
Cheers
