### ISSUE TITLE
connection failed: (10, 'authentication failed')

### ISSUE THREAD

**Issue by dingucosii** [SUSE/hanadb_exporter#82]
run cmd with the follow error:
hdbcli.dbapi.Error: (10, 'authentication failed')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/hanadb_exporter", line 9, in <module>
    main.run()
  File "/usr/lib/python3.6/site-packages/hanadb_exporter/main.py", line 134, in run
    timeout=config.get('timeout', 600))
  File "/usr/lib/python3.6/site-packages/hanadb_exporter/db_manager.py", line 130, in start
    self._connect_tenants(host, connection_data)
  File "/usr/lib/python3.6/site-packages/hanadb_exporter/db_manager.py", line 64, in _connect_tenants
    host, tenant_port, **connection_data)
  File "/usr/lib/python3.6/site-packages/shaptools/hdb_connector/connectors/dbapi_connector.py", line 58, in connect
    raise base_connector.ConnectionError('connection failed: {}'.format(err))
shaptools.hdb_connector.connectors.base_connector.ConnectionError: connection failed: (10, 'authentication failed')

**Comment by arbulu89** [comment]
Hi @dingucosii ,

We cannot help much with a such unclear description.
- How are you using the tool? Are you using the daemon option?
- Which command are you running?
- How is composed your configuration file?
- Can you access the database with other toools (hdbsql for example)?

Try to be as descriptive as possible please.

**Comment by dingucosii** [comment]
hi @arbulu89  
This is my configuration and run command：
![image](https://user-images.githubusercontent.com/4088658/112437709-30dd3380-8d82-11eb-8586-085f9528f860.png)

![image](https://user-images.githubusercontent.com/4088658/112437957-80bbfa80-8d82-11eb-8c90-18056ae755d1.png)

**Comment by arbulu89** [comment]
Hi @dingucosii Thanks for the information.
Unfortunately I cannot tell much...
Did you create the new users following this rules? https://github.com/SUSE/hanadb_exporter#create-a-new-user-with-monitoring-role

To pin-point a little bit more, you could try the next to see if the issue is with the database or the code itself:
```
linux:~ # python3
Python 3.6.13 (default, Mar 10 2021, 18:30:35) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hdbcli import dbapi
>>> dbapi.connect(address='localhost', port=30013, user='ZABBIX', password='My110Password')
<pyhdbcli.Connection object at 0x7f75cf67a270>
>>> dbapi.connect(address='localhost', port=30015, user='ZABBIX', password='My110Password')
<pyhdbcli.Connection object at 0x7f75cf67a390>
>>> 
```
If any of those raises the `authentication error` I could say that there is something wrong in this user or tenants configuration.

You can always try creating a new user

**Comment by dingucosii** [comment]
hi @arbulu89
I created  user ,according to your rules, follow your python cmd  can not  raises the authentication error . 

![image](https://user-images.githubusercontent.com/4088658/112563513-78ac9b00-8e14-11eb-8544-3d4a6283a32f.png)

**Comment by dingucosii** [comment]
![image](https://user-images.githubusercontent.com/4088658/112613878-94875f80-8e5b-11eb-94d2-2caa5b886a7f.png)

**Comment by arbulu89** [comment]
Hi @dingucosii ,
Try the next:
1. Modify the `logging_config.ini` file to increase the verbosity level. Replace the `WARNING` word by `DEBUG` in the whole file (or you could remove the `logging` entry from the config.json configuration file and use the `-v DEBUG` flag in the `hanadb_exporter` call
2. Repate the execution
3. Check and upload here the `hanadb_exporter.log` content (or the screen output, it should be the same)

**Comment by dingucosii** [comment]
hi @arbulu89,follow  your step ,see the next:
![image](https://user-images.githubusercontent.com/4088658/112921820-08688700-913e-11eb-833e-efbc05a32c70.png)

**Comment by arbulu89** [comment]
@dingucosii Is the connection allowed in the 2 tenants (`MGD` and `MGX`). The exporter will try to connect to the SYSTEMD and all the tenants with the provided user/password.
In previous logs you only confirmed that the connection to `MGD` works, but maybe the connection to `MGX` doesn't.
Remember that the used user/password must be in all the tenants. Here the conneection to `MGX` fails according the logs.
You will need to duplicate the user and role creation in this tenant too

**Comment by dingucosii** [comment]
@arbulu89 Thank you very much for your answers！

**Comment by arbulu89** [comment]
@dingucosii Did this work? If this is the case we can close the ticket

**Comment by dingucosii** [comment]
@arbulu89 you can close it ,thanks!
