### ISSUE TITLE
connection failed: (4321, 'only secure connections are allowed')

### ISSUE THREAD

**Issue by artgenose** [SUSE/hanadb_exporter#95]
Hi,

we are facing an issue with our HANA databases where SSL connections are enforced for security reasons with the following configuration parameter:

`global.ini / communication / sslenforce = true`

hanadb_exporter throws the following error message:

`hanadb_exporter.db_manager the connection to the system database failed. error message: connection failed: (4321, 'only secure connections are allowed')`
`hanadb_exporter Traceback (most recent call last):`
`  File "/usr/bin/hanadb_exporter", line 9, in <module>`
`    main.run()`
`  File "/usr/lib/python3.4/site-packages/hanadb_exporter/main.py", line 134, in run`
`    timeout=config.get('timeout', 600))`
`  File "/usr/lib/python3.4/site-packages/hanadb_exporter/db_manager.py", line 127, in start`
`    'timeout reached connecting the System database')`
`ConnectionError: timeout reached connecting the System database`

Is there a way to connect to the database using SSL?

**Comment by arbulu89** [comment]
Hi @artgenose ,
Honestly, I have not tried this scenario. We would need to research about it to see how the SSL communication works, but this won't happen shortly. Feel free to contribute here with a code change or just even explaining how this should be done adding some documentation page, this would speed up the implementation for sure.

**Comment by artgenose** [comment]
Thank you for your instant reply! I'll investigate the issue further hoping to find matching infos, but I'm unfortunately not able to provide a code change :/

PS: Thank you for your great work on hanadb_exporter! This tool is much appreciated.

**Comment by arbulu89** [comment]
@artgenose In a quick check, I found this blog with interesting information: https://blogs.sap.com/2020/05/07/secure-connection-from-python-to-sap-hana/

According this, the implementation wouldn't be that difficult. I will see if I can get some time to work on this during the next 2 weeks, and come to you if I get the feature implemented

**Comment by artgenose** [comment]
Thank you for looking into this issue! This sounds like a great solution.

**Comment by arbulu89** [comment]
Hi @artgenose ,
I have implemented this feature in: https://github.com/SUSE/hanadb_exporter/pull/96
